### ISSUE TITLE
这个是什么情况，点不了

### ISSUE THREAD

**Issue by 2107708125** [yatyricky/core-values-encoder-crx#2]
![qq 20180522202250](https://user-images.githubusercontent.com/36875929/40362091-2116163a-5dfe-11e8-9eb8-60ddc817c06b.png)

**Comment by yatyricky** [comment]
操作方式是：在网页中选择文本，然后点插件按钮

**Comment by yatyricky** [comment]
插件页面不算网页，故无任何显示，建议去常规网页尝试
